name: Repertoire
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Repertoire-Server
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - database

  database:
    image: "postgres:17"
    container_name: Repertoire-Database
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
