name: repertoire
services:
  storage:
    build: 
      context: .
      args:
        SERVER_PORT: ${SERVER_PORT}
    container_name: Repertoire-Storage
    env_file: ".env"
    environment:
      - IS_RUNNING_IN_CONTAINER=true
      - SERVER_HOST=0.0.0.0
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ${UPLOAD_DIRECTORY}:/${UPLOAD_DIRECTORY}
